language: java
sudo: required
addons:
  ulimit:
    nofile: 1048576
before_install:
- curl -nfsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
script: "./gradlew clean test jar"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TPMHv3LUWpuX9Njo1A7zsrNk6Z0FDRv2xOG6lmxboiEg1nNX/ctfJfGpHpMbTnc1Q23ycVMj8DBoTG/gy7+2Qd9m6WY7JN0MmvYdhATKFWvRhnkJD0Jkt+yAkWYJfAIv7MOh0JFstC/9HZGgfvkIDaZPk3PhXN+6KpJVWPTqf6+g8lgtncrqM2GS03dArwzhnxdj0rQ+jQ0xjONcBpVPKBwcljTo3p3A6JtAlvtrXsVyswi9HZHZ9USS4CDYlwljDHjc/wtjrGK+td9kR45kxt0aBUWAdUKx0ueH1GB/h2H3AS8chy9fUttqSynY6fY+/a1gwt3TBtw6KeY5adn89YzxybH3Nj006ilb8wyARBHS6fsAvaKLBFrdoh9ayq8GAb/bvw+b+pO/L6aq/ZSLzeZrVKgpL6C+Zh2/0cZdWt/AaT9vszwShxqcbjmJdzuvAyLyaGx1ELFZTwf4HPE8JokQCaZY4SPe2HOOteh9yb3FDAwahuQVqHWTB5p1k0zUBz1GdokjMrJ28XJErKQvaI4HRmcwso8nU1bvVntkj4jB8OkJE+EL6MeqznNLnJD+akwj0q0QgSvTjpjeobgoCLic5MbcL32+D25PE+PaOM13IJMkCJBAPfUTgyU2ZV6x4Gy3SsOEndpvi9fRtsuj3AGCjpibp3wFHFt/XPChGX0=
  file: "./build/libs/mongoose-storage-driver-nfs.jar"
  on:
    tags: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "Qhzd7RD9jC/KQiI5eDXaZ9PN5Cevc/8clgMfHZM9P5f619cV7tEWIpjJyREG1qfi0pHVTWzWrQ439U3M2wcC4/g7n8wiXCW6q5xfw5e3V2LgX9AGB2byExJaW0Wh7Kv3zBNVkCdEVP4ZB2Q2SCYHNdT/7Y4QkpgdcSWRw9ZsZhUpyGMdg39LgBur3hRlRiTzKhmzYl1dEIsjhC5n2RALGWZEqJYHa6wxK3yHM/MaGu2ZItmOskPgyHaTP/lAeMWcxhlYez8Tkx/+vf7Xxf2QFWumAj+vYNBh4EgvtBfbpJA9FrDh6cjGf6BuTAvNiIK+NuiZcc93cJCm2PU6iUEMSbwLuyYvJu/mlz/lAcdhnY1lk6vMCV+uYoIQSihkUfyb34WkKMMoWuH9683lu8mjFzVB1WTKu6AlWzvkwqG7PyruP7OM3H9FOfih0KQ0kefiLwqcQirz6HJkNHe9Y+4glwtg3QqIfenhHsQlSiLbzBvy7lIaekDJP9pdpMgUHsn6g3cjCnhfSSRxVQ78TazZKFuQtpD/a3BUxI2Wj2T3rTLuJRgiPlcvzCpJI7LUIas6DTbH8TKdFTooMiz5CLdv++nx/dUGNvKd+/rK08anJJf3j3236JNis/UoOiqQEwTAkUrCEby/cNoB/b46o4Qn7kO91zBN2vDNuuDNkRpx8Fc="
  - secure: "SHfrsL1w2v7Wmm8/1sngWW8dByIQRdeBo6tPPpl+3YqQV97iPIizwUx9ehZ923WISC5NncE2xXOrZQDndd4dV58VnWTRqiHpSIKBfZG9qB+YRJWarYNlj1hI/zlU39ruVKpCz7kJ9qwh+cRbBi1DkO6ZqqY6e2ASX6vj4jBVivvSTY3PsB1li0choeQtkb4k+8oS0QT+CkQtLlalUGddJbxlFiEzttRQ1xCE9O6P3yWoc1kZjswcybyE4CbWdna+dvYN/m0Kc8GEEVz5stAkzqFGrKslI1hLrhPcpJp6H7KsCrmytQbcGQIBFdBZqll3CZUUiQDwLTefJPGDtR7SWUX+yFtP8hGo7Nn82ECaHd1cV2mWHA4wr9qjhLtArGBtogexIA04/7+im3YylrR0AVdxsvojj93F/Bg+4jYcXTuDEUOZlvv5tGZ9PkcDziJSjrjC+9VVV6cRlrYrvKc+u9Td8+R8xkGJSG9fLiv0U0tMy/YBNl08o8eYk17LNOe5QV/ObPVaA3rVduTnzkTa2HpSL+7zsu5znVAx/GMV6hlhg4f7kiXB+mERfK4+cB7P4ta8rQmWUS8wtlkk74ARzGereUc+bgEa7fEaqMRIOhVz7QPvVAHv1gMXO1BPgdftu/9xMaeXyvTishq/B4/7ClzUpZrZnrDJQRq6nU+amE8="
after_success:
- echo $DOCKER_PASS
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=emcmongoose/mongoose-storage-driver-nfs
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build --build-arg MONGOOSE_VERSION=next -f docker/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- export REPO=emcmongoose/mongoose-storage-driver-nfs-service
- export DRIVER_VERSION=$TAG
- docker build --build-arg DRIVER_VERSION=$TAG -f docker/Dockerfile.storage-driver-service -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
