language: java
sudo: required
addons:
  ulimit:
    nofile: 1048576
before_install:
- curl -nfsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
script: "./gradlew clean test jar"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VPthSAA9qZVz0IJi3JTpCmThWsE1/zgaYhw9nKeHJV2m+i8htNGh1otIgd6yWp4LFYAGVwfoIQxLvNF85jBXrjSReo/8MS/amoqVtFrLp4HzVBVWeU4ZbIfMLa3LK+Vlkd6qT8iphW7Tpq+r6Ka3G8eJLY9E9uoGsVIHfQ71OVF9plciXMMXD9DFWXfIIAaJIwM9+L7ymHIS1WjhEcsE+zg1CJxbQ25KGcG2oGn1vJOtf+bxpYqAilRLSL0/l5zTkZT5LzJhKFAJIytbyGQVp2+PqZvpVs4P51BsRjWwuNjWsLqbpiO8SOIjuGR665RzbqQH0I063CWx0qecMH8HneXePzUpo6jlJKm6awOZPq6OAkMhtRQ70eMgawaD3CMKLgX+WnkYPlUS5s3oPX3U8AHVjqqrB1uIDlnTead6vrd0Kegw7L13USN+M374MfLe4OpTyfxchhW/anTqB5J/UNkOF+6ARKNCX7FTiZ7CPr7bpp7JAke6wf4xcxQvozFSXe7kXjPID+4d4ysscoBZdqhrsTGNl5MVA+kHREroC6Pyb4BoZQ8gdWDni3+Qxp+KHUCFa61/pIZjt4yLHzgWoM9rMIdwkamGEc2vsn5256eXjDCtK3jXEEHEqRw3Acu0akTMHAATNpKLUwdNLUcGRgqTLtd+Fq1Jq0cAP+mfHt8=
  file: "./build/libs/mongoose-storage-driver-nfs.jar"
  on:
    tags: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "OwLslnSH5NIAr4gci2PU9ByPqzKRaqxkG4bldenRBht82xFSrl/yperqY3ELyKjg0WZR0ZRF7inpWhq0rNholrUNZT+sGW0lwJngN5Eu5k9ycR2IjZFtReqAjLnEYN5ladIyi+1igcGJVo0cgTb1Lc66+fMeSVY4YROHIU4qxa/ANf9eB7W1+NpZCxR3NVbdsrhUwiNsi9o5YSrhtwiwJS8NoRcfuTQokpl/LtN92ZgRJozex8Gf9ZbCFsxIzdQ6QDuekGxlw5RdBd2VZ/dL+vXwIc9E3K8uB14/ilGszsu7Qfic0365xETZbvV8jmRZ3b+cBhZCTPjJogt4TNwUwPsrGaSOUbROXUzJUVHj6tzD7Qjwxp4IBcNpcV2tzG4Vc8WERRkMjG0jSj03ePzUMdFH2CJjZKm0NX8mH2OkUgikC3hoYXPHIIWLVAjeei09r8fGxHUwtgMIQbFIVfr20A8dnz1h3Tt525tm6fFXBS29hE48gjAhtVrXyXZEI5mRUCD7eb5L8HAlrNVaYdMC05cDSNAlRqrSachC9gOdoq4NDiHn3Q7ej9B6LPE8K/CUrNBuftrJeWa+XxUn58Vsh3XOsQb5NyRyUy+DxRpozBjr/9rAPYQSLfF2rsP38BfAbxI8N7ai/5yCY24a4MuzlAD1ST/M+uYzcsVHF+/Dt8o="
  - secure: "vJL5JZZt+m41QzPTXor5IJAHIFLRcLag7MqzNDH/8GWPVSD84GBBORJCXZbrvqTQkR+OgTd7w8J12Pvk7Wth7uA1GMb+gvWm/JytcHxN1b4tjg+Oh7Ug3KpVnIRjTRXw1AOpRjFmWlb2fmLRw0+jxehl6S9a8fixE2NOgQ6johWls2s9jA63Lum0U4CSiXKyCx6Ls2CkZQMZkI2RM9jF/zzOamNJCw+fipxwUV5ohaA374IePLdllEcoSrH74H8nxyzBcPmV0YAAJmN65UE4fhl3dkjJv1r+/vTfB7QQy/SMx1VpZ3Zowt+Gou/eKOOP9dK5gB/itJc/HegTFhD4mq2jKanIQUGp7JiZzVFenj3XL8nI5CL/nfr6GGF2IyLBnsimRgrfB8gWgdKLBjjSBRtZy2Ip62vNG65n6bBubDdHqPPVVPYW0zlbsSKvHpWY93Z541H3BABibn7B3PdoY1i+Kc/2uE6XPMckD4YQuqrmmymldtvc7Kdis2tiVGc2IiNkzUTVorPxnHYWvmBrUgreOpYIPYsi96raj1Ew6UQnCkm5jmf3nIDcF4x5/Ja/zhS5ThhxFMmCEd5AODShw1J/I9J8czxptam0OacUhot15xziieJMrh6CktaL5xg2gj0ab/zS53LTj/vs4cRHqkaTMDh2A1qC3yqGXRwOU8U="
after_success:
- echo $DOCKER_PASS
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=emcmongoose/mongoose-storage-driver-nfs
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build --build-arg MONGOOSE_VERSION=next -f docker/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- export REPO=emcmongoose/mongoose-storage-driver-nfs-service
- export DRIVER_VERSION=$TAG
- docker build --build-arg DRIVER_VERSION=$TAG -f docker/Dockerfile.storage-driver-service -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
